# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170208_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=1),
        ),
    ]
